/**
 * Tessera token compiler.
 *
 * Reads W3C design-token JSON (tokens/reference.json, tokens/semantic.json)
 * and emits:
 *   dist/tokens.css  - CSS custom properties inside @layer tessera.tokens
 *                      (reference tier on :root, semantic tier per [data-theme])
 *   dist/index.js    - typed JS maps (reference values, semantic aliases, cssVar helper)
 *   dist/index.d.ts
 *
 * Naming: token path "color.teal.500" -> CSS variable "--ts-color-teal-500".
 * Aliases "{color.teal.500}" compile to var(--ts-color-teal-500), so the
 * reference -> semantic relationship is preserved in the CSS output itself.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const PREFIX = "ts";

const reference = JSON.parse(readFileSync(join(root, "tokens/reference.json"), "utf8"));
const semantic = JSON.parse(readFileSync(join(root, "tokens/semantic.json"), "utf8"));

const isToken = (node) => node && typeof node === "object" && "$value" in node;

/** Flatten nested token JSON into [path, token] pairs. */
function flatten(node, path = []) {
  if (isToken(node)) return [[path.join("."), node]];
  return Object.entries(node).flatMap(([key, child]) => flatten(child, [...path, key]));
}

const toVarName = (path) => `--${PREFIX}-${path.replace(/\./g, "-")}`;

/** Compile "{color.teal.500}" aliases into var() references. */
const resolveValue = (value) =>
  String(value).replace(/\{([^}]+)\}/g, (_, path) => `var(${toVarName(path)})`);

const refTokens = flatten(reference);
const darkTokens = flatten(semantic.dark);
const lightTokens = flatten(semantic.light);

const mismatch = darkTokens
  .map(([p]) => p)
  .filter((p) => !lightTokens.some(([lp]) => lp === p));
if (mismatch.length > 0) {
  throw new Error(`Semantic tokens missing in light theme: ${mismatch.join(", ")}`);
}

const cssDecls = (tokens, indent = "    ") =>
  tokens.map(([path, t]) => `${indent}${toVarName(path)}: ${resolveValue(t.$value)};`).join("\n");

const css = `/* Generated by @tessera/tokens - do not edit by hand. */
@layer tessera.tokens {
  :root {
${cssDecls(refTokens)}
  }

  /* Tessera is dark-first: dark semantic tokens apply on :root by default. */
  :root,
  [data-theme="dark"] {
    color-scheme: dark;
${cssDecls(darkTokens)}
  }

  [data-theme="light"] {
    color-scheme: light;
${cssDecls(lightTokens)}
  }
}
`;

const jsObject = (entries) =>
  `{\n${entries.map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`).join("\n")}\n}`;

const refMap = refTokens.map(([path, t]) => [path, String(t.$value)]);
const semMap = darkTokens.map(([path, t]) => {
  const light = lightTokens.find(([lp]) => lp === path)[1];
  return [path, { dark: String(t.$value), light: String(light.$value) }];
});

const js = `/* Generated by @tessera/tokens - do not edit by hand. */
export const reference = ${jsObject(refMap)};

export const semantic = ${jsObject(semMap)};

export const themes = ["dark", "light"];

export const cssVar = (path) => \`var(--${PREFIX}-\${path.replace(/\\./g, "-")})\`;
`;

const dts = `/* Generated by @tessera/tokens - do not edit by hand. */
/** Reference-tier tokens: raw values keyed by dot path (e.g. "color.teal.500"). */
export declare const reference: Record<string, string>;
/** Semantic-tier tokens: per-theme alias values keyed by dot path (e.g. "bg.canvas"). */
export declare const semantic: Record<string, { dark: string; light: string }>;
export declare const themes: readonly ["dark", "light"];
/** Returns the CSS var() reference for a token path, e.g. cssVar("bg.canvas"). */
export declare const cssVar: (path: string) => string;
`;

mkdirSync(join(root, "dist"), { recursive: true });
writeFileSync(join(root, "dist/tokens.css"), css);
writeFileSync(join(root, "dist/index.js"), js);
writeFileSync(join(root, "dist/index.d.ts"), dts);

console.log(
  `@tessera/tokens: ${refTokens.length} reference + ${darkTokens.length} semantic tokens -> dist/tokens.css`
);
